MEstradaSanchez/DCFormacion

- force-app/main/default/layouts/Event-Formato de eventos.layout
- force-app/main/default/layouts/Task-Formato de tareas.layout
- force-app/main/default/objects/Activity/fields/Test_Nuevo_Campo__c.field-meta.xml
- force-app/main/default/profiles/Admin.profile
- force-app/main/default/profiles/Read Only.profile
> [DevOps Center] Merge WI-000001 to Integration

- force-app/main/default/layouts/Asset-Formato de activos.layout
- force-app/main/default/objects/Asset/fields/Test_Nuevo_Campo__c.field-meta.xml
- force-app/main/default/profiles/Admin.profile
- force-app/main/default/profiles/Read Only.profile
> [DevOps Center] Merge WI-000003 to Staging

- force-app/main/default/layouts/Event-Formato de eventos.layout
- force-app/main/default/layouts/Task-Formato de tareas.layout
- force-app/main/default/objects/Activity/fields/TestDevOps__c.field-meta.xml
- force-app/main/default/profiles/Admin.profile
- force-app/main/default/profiles/Read Only.profile
> [DevOps Center] Merge WI-000005 to Integration

- force-app/main/default/layouts/Event-Formato de eventos.layout
- force-app/main/default/layouts/Task-Formato de tareas.layout
- force-app/main/default/objects/Activity/fields/TestDevOps__c.field-meta.xml
- force-app/main/default/profiles/Admin.profile
- force-app/main/default/profiles/Read Only.profile
> [DevOps Center] Merge WI-000005 to UAT

- force-app/main/default/layouts/Account-Formato de cuentas.layout
- force-app/main/default/objects/Account/fields/TestFran__c.field-meta.xml
- force-app/main/default/objects/Account/fields/TestWI_DevOps__c.field-meta.xml
- force-app/main/default/profiles/Admin.profile
- force-app/main/default/profiles/Read Only.profile
> [DevOps Center] Merge WI-000007 to Integration

- force-app/main/default/objects/Activity/fields/TestDevOps__c.field-meta.xml
- force-app/main/default/profiles/Admin.profile
- force-app/main/default/profiles/Read Only.profile
> [DevOps Center] Merge WI-000009 to Integration

- force-app/main/default/classes/MaskEmail.cls
> [DevOps Center] Merge WI-000010 to Integration

- force-app/main/default/layouts/Event-Formato de eventos.layout
- force-app/main/default/layouts/Task-Formato de tareas.layout
- force-app/main/default/objects/Activity/fields/TestDevOps__c.field-meta.xml
- force-app/main/default/profiles/Admin.profile
- force-app/main/default/profiles/Read Only.profile
> [DevOps Center] Merge WI-000005 to Staging

- force-app/main/default/classes/MaskEmail.cls
- force-app/main/default/layouts/Account-Formato de cuentas.layout
- force-app/main/default/objects/Account/fields/TestDeploy__c.field-meta.xml
- force-app/main/default/profiles/Admin.profile
- force-app/main/default/profiles/Read Only.profile
> [DevOps Center] Merge WI-000015 to Integration

- force-app/main/default/classes/MaskEmail.cls
> [DevOps Center] Merge WI-000017 to Integration

- force-app/main/default/classes/batchFieldsUpdate.cls
> [DevOps Center] Merge WI-000018 to Integration

- force-app/main/default/classes/batchFieldsUpdate.cls
> [DevOps Center] Merge WI-000019 to Integration

- force-app/main/default/classes/batchFieldsUpdate.cls
> [DevOps Center] Merge WI-000020 to Integration

- force-app/main/default/classes/batchFieldsUpdate.cls
> [DevOps Center] Merge WI-000021 to Integration

- force-app/main/default/classes/batchFieldsUpdate.cls
> [DevOps Center] Merge WI-000018 to UAT

- force-app/main/default/classes/batchFieldsUpdate.cls
> [DevOps Center] Merge WI-000022 to UAT

- force-app/main/default/classes/batchFieldsUpdate.cls
> [DevOps Center] Merge WI-000022 to Staging

- force-app/main/default/profiles/Admin.profile
- force-app/main/default/profiles/Read Only.profile
> [DevOps Center] Merge WI-000007 to UAT

- force-app/main/default/objects/Activity/fields/TestDevOps__c.field-meta.xml
- force-app/main/default/profiles/Admin.profile
- force-app/main/default/profiles/Read Only.profile
> [DevOps Center] Merge WI-000009 to UAT

- force-app/main/default/classes/MaskEmail.cls
> [DevOps Center] Merge WI-000010 to Staging

- force-app/main/default/classes/MaskEmail.cls
> [DevOps Center] Merge WI-000017 to UAT

- force-app/main/default/classes/MaskEmail.cls
- force-app/main/default/layouts/Account-Formato de cuentas.layout
- force-app/main/default/objects/Account/fields/TestDeploy__c.field-meta.xml
- force-app/main/default/profiles/Admin.profile
- force-app/main/default/profiles/Read Only.profile
> [DevOps Center] Merge WI-000016 to UAT

- force-app/main/default/layouts/Asset-Formato de activos.layout
- force-app/main/default/objects/Asset/fields/Prueba1__c.field-meta.xml
- force-app/main/default/profiles/Admin.profile
Centro de DevOps creó esta solicitud de extracción. Se convertirá automáticamente al promocionar en Centro de DevOps. Si la combina fuera de Centro de DevOps, Centro de DevOps le proporciona la opción de implementar los cambios para completar la promoción.
> Combinación de [Centro de DevOps] de WI-000023 a Integration

- force-app/main/default/objects/Account/fields/TestDeploy__c.field-meta.xml
> [DevOps Center] Merge WI-000026 to Integration

- force-app/main/default/objects/Account/fields/TestDeploy__c.field-meta.xml
> [DevOps Center] Merge WI-000027 to Integration

- force-app/main/default/classes/MaskEmail.cls
> [DevOps Center] Merge WI-000028 to Integration

- force-app/main/default/classes/MaskEmail.cls
- force-app/main/default/layouts/Account-Formato de cuentas.layout
- force-app/main/default/objects/Account/fields/Test_Sync__c.field-meta.xml
- force-app/main/default/profiles/Admin.profile
- force-app/main/default/profiles/Read Only.profile
> [DevOps Center] Merge WI-000029 to Integration

- force-app/main/default/objects/Account/fields/TestDeploy__c.field-meta.xml
> [DevOps Center] Merge WI-000027 to UAT

- force-app/main/default/classes/MaskEmail.cls
- force-app/main/default/layouts/Account-Formato de cuentas.layout
- force-app/main/default/objects/Account/fields/Test_Sync__c.field-meta.xml
- force-app/main/default/profiles/Admin.profile
- force-app/main/default/profiles/Read Only.profile
> [DevOps Center] Merge WI-000029 to UAT

- force-app/main/default/classes/MaskEmail.cls
> [DevOps Center] Merge WI-000031 to Integration

- force-app/main/default/classes/MaskEmail.cls
> [DevOps Center] Merge WI-000032 to Integration

- force-app/main/default/classes/MaskEmail.cls
> [DevOps Center] Merge WI-000032 to UAT
